function palavraRadom() {

    const lista = [
        { palavra: 'MACACO', dica: 'ANIMAL' },
        { palavra: 'CACHORRO', dica: 'ANIMAL DOMÉSTICO' },
        { palavra: 'GATO', dica: 'ANIMAL FELINO' },
        { palavra: 'ELEFANTE', dica: 'ANIMAL GIGANTE' },
        { palavra: 'CROCODILO', dica: 'ANIMAL RÉPTIL' },
        { palavra: 'GIRAFA', dica: 'ANIMAL DE PESCOÇO LONGO' },
        { palavra: 'LEAO', dica: 'REI DA SELVA' },
        { palavra: 'TIGRE', dica: 'ANIMAL LISTRADO' },
        { palavra: 'ZEBRA', dica: 'ANIMAL LISTRADO' },
        { palavra: 'BESOURO', dica: 'INSETO' },
        { palavra: 'BORBOLETA', dica: 'INSETO COLORIDO' },
        { palavra: 'ABELHA', dica: 'INSETO QUE PRODUZ MEL' },
        { palavra: 'FORMIGA', dica: 'INSETO TRABALHADOR' },
        { palavra: 'LIBELULA', dica: 'INSETO VOADOR' },
        { palavra: 'ARANHA', dica: 'ARACNÍDEO' },
        { palavra: 'ESCOVA', dica: 'OBJETO PARA PENTEAR CABELO' },
        { palavra: 'CANETA', dica: 'OBJETO PARA ESCREVER' },
        { palavra: 'CADERNO', dica: 'OBJETO PARA ANOTAR' },
        { palavra: 'LAPIS', dica: 'OBJETO PARA DESENHAR' },
        { palavra: 'TESOURA', dica: 'OBJETO PARA CORTAR' },
        { palavra: 'MARTELO', dica: 'OBJETO PARA BATER' },
        { palavra: 'CHAVE', dica: 'OBJETO PARA ABRIR FECHADURAS' },
        { palavra: 'ANEL', dica: 'OBJETO PARA USAR NO DEDO' },
        { palavra: 'COLAR', dica: 'OBJETO PARA USAR NO PESCOÇO' },
        { palavra: 'BRINCO', dica: 'OBJETO PARA USAR NA ORELHA' },
        { palavra: 'RELOGIO', dica: 'OBJETO PARA VER AS HORAS' },
        { palavra: 'SOFA', dica: 'MÓVEL PARA SENTAR' },
        { palavra: 'CADEIRA', dica: 'MÓVEL PARA SENTAR' },
        { palavra: 'MESINHA', dica: 'MÓVEL PARA APOIAR OBJETOS' },
        { palavra: 'MESA', dica: 'MÓVEL PARA APOIAR OBJETOS' },
        { palavra: 'ESTANTE', dica: 'MÓVEL PARA GUARDAR LIVROS' },
        { palavra: 'GUARDAROUPA', dica: 'MÓVEL PARA GUARDAR ROUPAS' },
        { palavra: 'ARMARIO', dica: 'MÓVEL PARA GUARDAR OBJETOS' },
        { palavra: 'PIANO', dica: 'INSTRUMENTO MUSICAL' },
        { palavra: 'VIOLINO', dica: 'INSTRUMENTO MUSICAL' },
        { palavra: 'FLAUTA', dica: 'INSTRUMENTO MUSICAL DE SOPRO' },
        { palavra: 'TAMBOR', dica: 'INSTRUMENTO MUSICAL DE PERCUSSÃO' },
        { palavra: 'GUITARRA', dica: 'INSTRUMENTO MUSICAL DE CORDAS' },
        { palavra: 'FACA', dica: 'OBJETO CORTANTE' },
        { palavra: 'GARFO', dica: 'OBJETO PARA COMER' },
        { palavra: 'COLHER', dica: 'OBJETO PARA COMER' },
        { palavra: 'PRATO', dica: 'OBJETO PARA SERVIR COMIDA' },
        { palavra: 'COPO', dica: 'OBJETO PARA BEBER' },
        { palavra: 'GARRAFA', dica: 'OBJETO PARA GUARDAR LÍQUIDOS' },
        { palavra: 'TRAVESSEIRO', dica: 'OBJETO PARA APOIAR A CABEÇA' },
        { palavra: 'LENCOL', dica: 'OBJETO PARA COBRIR A CAMA' },
        { palavra: 'EDREDOM', dica: 'OBJETO PARA AQUECER NA CAMA' },
        { palavra: 'TRAVESSEIRO', dica: 'OBJETO PARA APOIAR A CABEÇA NA CAMA' },
        { palavra: 'CADEADO', dica: 'OBJETO PARA TRANCAR' },
        { palavra: 'CARTAO', dica: 'OBJETO PARA PAGAR' },
        { palavra: 'CARTEIRA', dica: 'OBJETO PARA GUARDAR DINHEIRO' },
        { palavra: 'CHAVEIRO', dica: 'OBJETO PARA GUARDAR CHAVES' },
        { palavra: 'RELOGIO', dica: 'OBJETO PARA MEDIR O TEMPO' },
        { palavra: 'TELEVISAO', dica: 'ELETRODOMÉSTICO PARA ASSISTIR PROGRAMAS' },
        { palavra: 'GELADEIRA', dica: 'ELETRODOMÉSTICO PARA CONSERVAR ALIMENTOS' },
        { palavra: 'FOGAO', dica: 'ELETRODOMÉSTICO PARA COZINHAR' },
        { palavra: 'MAQUINA DE LAVAR', dica: 'ELETRODOMÉSTICO PARA LAVAR ROUPAS' },
        { palavra: 'ASPIRADOR DE PO', dica: 'ELETRODOMÉSTICO PARA LIMPAR O CHÃO' },
        { palavra: 'MICROONDAS', dica: 'ELETRODOMÉSTICO PARA AQUECER COMIDA RÁPIDA' },
        { palavra: 'LIQUIDIFICADOR', dica: 'ELETRODOMÉSTICO PARA FAZER SUCOS' },
        { palavra: 'CAFETEIRA', dica: 'ELETRODOMÉSTICO PARA FAZER CAFÉ' },
        { palavra: 'TORRADEIRA', dica: 'ELETRODOMÉSTICO PARA TORRAR PÃO' },
        { palavra: 'VENTILADOR', dica: 'ELETRODOMÉSTICO PARA REFRESCAR O AMBIENTE' },
        { palavra: 'AR CONDICIONADO', dica: 'ELETRODOMÉSTICO PARA REFRESCAR O AMBIENTE' },
        { palavra: 'ABAJUR', dica: 'OBJETO PARA ILUMINAR' },
        { palavra: 'LUSTRE', dica: 'OBJETO PARA ILUMINAR O AMBIENTE' },
        { palavra: 'LAMPADA', dica: 'OBJETO PARA ILUMINAR' },
        { palavra: 'VELA', dica: 'OBJETO PARA ILUMINAR E PERFUMAR' },
        { palavra: 'BICICLETA', dica: 'MEIO DE TRANSPORTE COM PEDAL' },
        { palavra: 'CARRO', dica: 'MEIO DE TRANSPORTE COM MOTOR' },
        { palavra: 'ONIBUS', dica: 'MEIO DE TRANSPORTE COLETIVO' },
        { palavra: 'TREM', dica: 'MEIO DE TRANSPORTE SOB TRILHOS' },
        { palavra: 'AVIAO', dica: 'MEIO DE TRANSPORTE AÉREO' },
        { palavra: 'NAVIO', dica: 'MEIO DE TRANSPORTE AQUÁTICO' },
        { palavra: 'MOTO', dica: 'MEIO DE TRANSPORTE COM MOTOR E DUAS RODAS' },
        { palavra: 'SKATE', dica: 'MEIO DE TRANSPORTE COM RODAS' },
        { palavra: 'PATINS', dica: 'MEIO DE TRANSPORTE COM RODAS' },
        { palavra: 'JATO', dica: 'MEIO DE TRANSPORTE VELOZ' },
        { palavra: 'FOGUETE', dica: 'MEIO DE TRANSPORTE PARA O ESPAÇO' },
        { palavra: 'BARRACA', dica: 'OBJETO PARA ACAMPAR' },
        { palavra: 'ISQUEIRO', dica: 'OBJETO PARA ACENDER FOGO' },
        { palavra: 'BINOCULO', dica: 'OBJETO PARA VER A DISTÂNCIA' },
        { palavra: 'BUSSOLA', dica: 'OBJETO PARA ORIENTAÇÃO' },
        { palavra: 'LANTERNA', dica: 'OBJETO PARA ILUMINAR' },
        { palavra: 'TENDA', dica: 'OBJETO PARA ACAMPAR' },
        { palavra: 'COLCHAO', dica: 'OBJETO PARA DORMIR' },
        { palavra: 'SACO DE DORMIR', dica: 'OBJETO PARA DORMIR' },
        { palavra: 'TRAVESSEIRO', dica: 'OBJETO PARA APOIAR A CABEÇA' },
        { palavra: 'PISCINA', dica: 'LOCAL PARA NADAR' },
        { palavra: 'RIO', dica: 'CURSO D ÁGUA NATURAL' },
        { palavra: 'LAGO', dica: 'CORPO D ÁGUA NATURAL' },
        { palavra: 'MAR', dica: 'CORPO D ÁGUA SALGADA' },
        { palavra: 'OCEANO', dica: 'CORPO D ÁGUA IMENSO' },
        { palavra: 'LIXEIRA', dica: 'RECIPIENTE PARA JOGAR LIXO' },
        { palavra: 'RECICLAGEM', dica: 'PROCESSO PARA REAPROVEITAR MATERIAIS' },
        { palavra: 'COMPOSTAGEM', dica: 'PROCESSO PARA DECOMPOSIÇÃO DE MATÉRIA ORGÂNICA' },
        { palavra: 'ECOLOGIA', dica: 'CIÊNCIA DO MEIO AMBIENTE' },
        { palavra: 'BIODIVERSIDADE', dica: 'VARIEDADE DE VIDA NO PLANETA' },
        { palavra: 'SUSTENTABILIDADE', dica: 'PRÁTICA PARA PRESERVAR RECURSOS NATURAIS' },
        { palavra: 'POLUIÇÃO', dica: 'CONTAMINAÇÃO DO MEIO AMBIENTE' },
        { palavra: 'DESERTO', dica: 'AMBIENTE ÁRIDO E SECO' },
        { palavra: 'FLORESTA', dica: 'AMBIENTE COM ÁRVORES' },
        { palavra: 'MONTANHA', dica: 'ELEVADA FORMAÇÃO GEOLÓGICA' },
        { palavra: 'PRAIA', dica: 'FAIXA DE TERRA PRÓXIMA AO MAR' },
        { palavra: 'CACHOEIRA', dica: 'QUEDA D ÁGUA NATURAL' },
        { palavra: 'AVENTURA', dica: 'EXPERIÊNCIA EXCITANTE' }
    ];

    return lista[numeroAleatorio()];


}

function numeroAleatorio() {
    return Math.floor(Math.random() * 101);
}